### ISSUE TITLE
Gracefully handle lines from newsyslog/logrotate/etc.

### ISSUE THREAD

**Issue by zi0r** [facundoolano/ngtop#18]
Today, ngtop breaks when it encounters lines that are added by newsyslog/logrotate, etc:

`ngtop: error: log line didn't match format:
              format:(?P<remote_addr>\S+) - (?:\S+) \[(?P<time_local>.*?)\] "(?P<request>.*?)" (?P<status>\S+) (?:\S+) "(?P<http_referer>.*?)" "(?P<http_user_agent>.*?)"
              line:Jul 31 01:00:00 xxx newsyslog[32770]: logfile turned over due to size>40560K`

**Comment by facundoolano** [comment]
fixed, thanks for reporting.
