### ISSUE TITLE
Unable to install it on Ubuntu 20

### ISSUE THREAD

**Issue by Grachy** [facundoolano/ngtop#23]
At first I tried using this 
```
wget https://github.com/facundoolano/ngtop/releases/latest/download/ngtop-linux-arm64  \
    -O ngtop && chmod +x ngtop && mv ngtop /usr/local/bin
```
It didn't work at all even after manually trying each part, than I decided to try installing it with Go.

I did install Go, but this command didn't work either
`go install github.com/facundoolano/ngtop@latest`

I am gettin an error "can't load package: package github.com/facundoolano/ngtop@latest: can only use path@version syntax with 'go get'"

After working around I figured out my Go version was wrong, I installed 1.22 and it worked, but nothing was installed after running
`go install github.com/facundoolano/ngtop@latest`

Nothing happens, I can't use [ngtop], I get an error: 
"ngtop: command not found"

Can you make a more detailed installation manual?

**Comment by Grachy** [comment]
Sure, right now it goes like this

https://i.imgur.com/VsMtxYU.jpeg

**Comment by facundoolano** [comment]
> Exec format error usually means that the binary is for a different cpu or different libc

You probably need to try the amd64 binary instead of the arm64 one

**Comment by Grachy** [comment]
That helped, but now it requires some lib:
```
ngtop -s 1h --limit 5

ngtop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ngtop)
ngtop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ngtop)
ngtop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ngtop)
```

**Comment by facundoolano** [comment]
I see, there may be some issues in the compilation flags. I'll look into this

**Comment by Grachy** [comment]
> download/test-6/ngtop-linux-amd64

I think I managed to install it now, but I typed this by mistake:
" ngtop url user_agent -s 3d --where url="

And now I've got an error:
`ngtop: error: database is locked`

I tried killing ngtop process, that didn't help, is there a way to kill that operation in sqlite?

**Comment by facundoolano** [comment]
The command seems valid. Can you run with the `NGTOP_DEBUG=1` environment and share the logs?

you may be able to workaround the error by removing or renaming the ngtop.db file.
