### ISSUE TITLE
How to aggregate by field $remote_user

### ISSUE THREAD

**Issue by MaximeMaW** [facundoolano/ngtop#25]
I want to output statistics by user (field $remote_user in my nginx logs). I did not find how to aggregate by such variable. How is it possible? Is it a feature missing?

Thanks!

**Comment by facundoolano** [comment]
Hi @MaximeMaW, yes that field is missing, thanks for reporting. I just added it and published a new version of the program. 

You should be able to refer to it as `remote_user` or just `user` in the CLI, let me know if it works as expected.
